### ISSUE TITLE
Можно было бы использовать методы массива для этого

### ISSUE THREAD

**Issue by PavloKovalov** [Crypto-kittensSeller/wg_forge_tasks#1]
https://github.com/Crypto-kittensSeller/wg_forge_tasks/blob/7b7b1313b8d25f2f2eb468d0a13abacfe15dc9b3/01_basics_part_1/exercises/queue.js#L34

**Comment by PavloKovalov** [comment]
и тут

https://github.com/Crypto-kittensSeller/wg_forge_tasks/blob/7b7b1313b8d25f2f2eb468d0a13abacfe15dc9b3/01_basics_part_1/exercises/stack.js#L35

**Comment by Crypto-kittensSeller** [comment]
Refactored using array method
