### ISSUE TITLE
Костыльная реализации генератора

### ISSUE THREAD

**Issue by artur-code** [Crypto-kittensSeller/wg_forge_tasks#2]
https://github.com/Crypto-kittensSeller/wg_forge_tasks/blob/7b7b1313b8d25f2f2eb468d0a13abacfe15dc9b3/exercises/functions.js#L46

Менять свойства функции это плохая практика, данную задача нужно решать через замыкания (подробнее разберем на 4 - 5 занятии)

**Comment by Crypto-kittensSeller** [comment]
Refactored using closure
